version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:135246@db/mysql
    depends_on:
      - db
    ports:
      - "8800:8800"
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 135246
      MYSQL_DATABASE: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
